//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMp_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EmpID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string jobd { get; set; }
    }
}
