// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailwayManagementSystem.Data;

#nullable disable

namespace RailwayManagementSystem.Migrations
{
    [DbContext(typeof(RailwayDbContext))]
    [Migration("20230810082657_fuu")]
    partial class fuu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Class_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fare")
                        .HasColumnType("int");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<string>("TDCID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TDCID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Passenger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Ticket_detail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Class_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Passenger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Seat_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Train_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("TicketDetails");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Train_Detail_Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("TrainDetailClass");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Train_detail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Arr_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDeparture")
                        .HasColumnType("date");

                    b.Property<string>("Dept_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TDCID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Train_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TDCID");

                    b.ToTable("TrainDetails");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Class", b =>
                {
                    b.HasOne("RailwayManagementSystem.Models.DbModels.Train_Detail_Class", "Train_Detail_Classes")
                        .WithMany("Classes")
                        .HasForeignKey("TDCID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train_Detail_Classes");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Payment", b =>
                {
                    b.HasOne("RailwayManagementSystem.Models.DbModels.Reservation", "Reservations")
                        .WithOne("Payment")
                        .HasForeignKey("RailwayManagementSystem.Models.DbModels.Payment", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Reservation", b =>
                {
                    b.HasOne("RailwayManagementSystem.Models.DbModels.Train_detail", "Train_detail")
                        .WithMany("Reservations")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwayManagementSystem.Models.DbModels.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train_detail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Ticket_detail", b =>
                {
                    b.HasOne("RailwayManagementSystem.Models.DbModels.Payment", "Payment")
                        .WithOne("Ticket_Details")
                        .HasForeignKey("RailwayManagementSystem.Models.DbModels.Ticket_detail", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Train_detail", b =>
                {
                    b.HasOne("RailwayManagementSystem.Models.DbModels.Train_Detail_Class", "Train_Detail_Classes")
                        .WithMany("TrainDetails")
                        .HasForeignKey("TDCID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train_Detail_Classes");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.User", b =>
                {
                    b.HasOne("RailwayManagementSystem.Models.DbModels.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Payment", b =>
                {
                    b.Navigation("Ticket_Details");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Reservation", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Train_Detail_Class", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("TrainDetails");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.Train_detail", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RailwayManagementSystem.Models.DbModels.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
